# Generated by Django 2.2.4 on 2020-01-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_productora', models.CharField(max_length=200, verbose_name='Nombre Productora')),
                ('imagen_productora', sorl.thumbnail.fields.ImageField(blank=True, help_text='Tamaño 664x362', max_length=200, null=True, upload_to='productoras/', verbose_name='Imagen Productora')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('imagen_programa', sorl.thumbnail.fields.ImageField(blank=True, help_text='Tamaño 664x362', max_length=200, null=True, upload_to='programas/', verbose_name='Imagen Programa')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('productora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Productora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_capitulo', models.IntegerField(verbose_name='Numero')),
                ('fecha_emision', models.DateTimeField(verbose_name='Fecha de emision')),
                ('titulo', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('imagen_principal', sorl.thumbnail.fields.ImageField(blank=True, help_text='Tamaño 664x362', max_length=200, null=True, upload_to='capitulos/', verbose_name='Imagen Principal')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa', to='web.Programa')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['numero_capitulo'],
            },
        ),
    ]
