# Generated by Django 2.2.4 on 2020-01-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200120_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulos',
            options={'ordering': ['-numero_capitulo']},
        ),
        migrations.AddField(
            model_name='programa',
            name='orden_programa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden Programa'),
        ),
    ]
