# Generated by Django 2.2.4 on 2020-01-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200125_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_video_principal', models.CharField(max_length=200, verbose_name='Nombre Video Principal')),
                ('video_principal', models.URLField(blank=True, null=True, verbose_name='Video Principal')),
                ('videos_activo', models.BooleanField(default=True, verbose_name='Video Activo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['orden_programa']},
        ),
    ]
