# Generated by Django 2.2.4 on 2020-02-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200207_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='nombre_productora_por_capitulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Productora por Capitulo'),
        ),
    ]
