# Generated by Django 2.2.4 on 2020-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_capitulos_nombre_productora_por_capitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='mostrar_principal',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
