# Generated by Django 2.2.4 on 2020-09-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_capitulos_mostrar_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='mostrar_principal',
            field=models.BooleanField(default=True, verbose_name='Mostrar en principal'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='orden_programa',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Orden Programa'),
        ),
    ]
