# Generated by Django 2.2.4 on 2020-09-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200906_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='titulo',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='Titulo'),
        ),
    ]
