# Generated by Django 2.2.4 on 2020-09-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200907_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='order_video',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Orden del Videos'),
        ),
    ]
