# Generated by Django 3.0 on 2020-10-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_principal_order_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulos',
            options={'ordering': ['-numero_capitulo'], 'verbose_name': 'Capitulo', 'verbose_name_plural': 'Capitulos'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['order_video'], 'verbose_name': 'Video Principal', 'verbose_name_plural': 'Videos Principales'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['orden_programa'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterField(
            model_name='capitulos',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Tamaño 664x362', max_length=200, null=True, upload_to='capitulos/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='capitulos',
            name='logo_titulo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_titulos/', verbose_name='Logo Titulo'),
        ),
        migrations.AlterField(
            model_name='productora',
            name='imagen_productora',
            field=models.ImageField(blank=True, help_text='Tamaño 664x362', max_length=200, null=True, upload_to='productoras/', verbose_name='Imagen Productora'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='imagen_programa',
            field=models.ImageField(blank=True, help_text='Tamaño 664x362', max_length=200, null=True, upload_to='programas/', verbose_name='Imagen Programa'),
        ),
    ]
